-- Create the messages table
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    author TEXT NOT NULL,
    text TEXT NOT NULL
);

-- Enable Realtime for the messages table
-- Go to Supabase Database -> Replication -> Click '1 table' and toggle 'messages' ON
ALTER PUBLICATION supabase_realtime ADD TABLE messages;

-- Insert the default conversation history (optional, so it's not empty!)
INSERT INTO messages (author, text) VALUES
  ('regina', 'laper'),
  ('aldo', 'makan'),
  ('regina', 'makan bareng'),
  ('aldo', 'makan apa'),
  ('regina', 'mie'),
  ('aldo', 'bikin dirumah juga bisa itu mah!!!!!'),
  ('regina', 'gabisa'),
  ('aldo', 'TINGGAL BELI MIE TRS REBUS'),
  ('regina', 'maunya mie and you');

-- Create the users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    user_key TEXT NOT NULL
);

-- Insert the default users
INSERT INTO users (username, password, user_key) VALUES 
('reginahenpiaoliang', '1802', 'regina'),
('aldo', '0904', 'aldo');
